# Generated by Django 4.0.5 on 2022-06-23 17:58

import controlmigratorio.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('pasaporte', models.IntegerField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=300)),
                ('segundo_nombre', models.CharField(max_length=300)),
                ('primer_apellido', models.CharField(max_length=300)),
                ('segundo_apellido', models.CharField(max_length=300)),
                ('alerta_migratoria', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'ordering': ['pasaporte'],
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_departamento', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_municipio', models.CharField(max_length=100)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controlmigratorio.departamento')),
            ],
            options={
                'verbose_name': 'Municipio',
                'verbose_name_plural': 'Municipios',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_movimiento', models.CharField(choices=[(controlmigratorio.models.MovimientoEnum['SA'], 'Salida del país'), (controlmigratorio.models.MovimientoEnum['IN'], 'Ingreso al país')], max_length=5)),
                ('fecha_movimiento', models.DateField()),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controlmigratorio.ciudadano')),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Movimientos',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='controlmigratorio.municipio'),
        ),
    ]
